services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=invoices'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=pguser'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'example@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres
    links:
      - postgres